plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
include ':app'
include ':cslibrary4a'
include ':epctagcoder'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url "https://repo.eclipse.org/content/repositories/paho-snapshots/" }
        maven { url "https://repo.eclipse.org/content/repositories/paho-releases/" }
    }
}